apiVersion: v1
kind: Service
metadata:
  name: backend  # ← DNS: backend.default.svc.cluster.local
spec:
  type: ClusterIP  # ← Vain klusterin sisäinen (ei ulkopuolista pääsyä)
  selector:
    app: backend
  ports:
  - port: 8000        
    targetPort: 8000  